language: ruby
cache: bundler
sudo: required

rvm:
  - 2.3.0

before_install:
  - wget https://gist.github.com/petere/5893799/raw/apt.postgresql.org.sh
  - wget https://gist.github.com/petere/6023944/raw/pg-travis-test.sh
  - sudo sh ./apt.postgresql.org.sh
env:
  - PGVERSION=9.5

services:
  - redis-server

before_script:
  - cp config/database.yml.travis config/database.yml

script:
  - 'bundle exec rake db:create'
  - 'bundle exec rspec'

notifications:
  email:
    recipients:
      - sebastian.schkudlara@vizzuality.com
    on_failure: change
    on_success: never

addons:
  code_climate:
    repo_token: 67a151976bb31c5bafef9c1dd2bdf0c68343f090d5c0be9069f2397cc8f2a0a2
